### ISSUE TITLE
Add page numbers to concept list

### ISSUE THREAD

**Issue by xrotwang** [lexibank/polyglottaafricana#8]
When the [concepts](https://github.com/lexibank/polyglottaafricana/blob/master/etc/concepts.tsv) are turned into a proper Concepticon concept list, this should include page numbers to identify relevant [scans](https://github.com/lexibank/polyglottaafricana/blob/master/raw/polyglottaafricana_scans.json) with the source data.

**Comment by LinguList** [comment]
Ah, @tresoldi, do you remember that we have the Koelle list already mapped? But since it was a bit difficult to deal with, we had it all on google drive, I think. Could you share the link here? Or let me know if you do not find it, I think it was @Kristina-Pianykh, who started to look into this list...

**Comment by tresoldi** [comment]
It is this one: https://docs.google.com/spreadsheets/d/10VrKzLbB65kSm7JYT4S7uJLqNR1jJZ6sESGECApMECg/edit#gid=223138965

I remember all the discussions about "nose ring" and all, and eye-balling it seems to be in line with the `concepts.tsv` I pushed in May. But I will double check and confirm with her and possibly @chrzyki .

**Comment by xrotwang** [comment]
page numbers (and thus scan numbers) are available in `raw/test-koelle.csv`
